### ISSUE TITLE
Needs comments about variables and figures involved in computations

### ISSUE THREAD

**Issue by erhanyasar** [kaantoprakk/roulette-animation#1]
Kaan merhaba,

Burayı sana erişmek için kullanmak istedim. Yeniden yazmaya çalışırken hesaplamanın anlamlandıramadığım sabit değerleri mevcut. Misal `assets/roulette.js: 126` ile belirttiğin  825 & 1125.

Github profilimdeki websitem üzerinden gerekirse telefonla arayarak ulaşabilirsen, bir projemde kullanmak üzere gerekirse ücreti karşılığında bilgi almak istiyorum mümkünse.

Sevgiler.

**Comment by kaantoprakk** [comment]
Merhaba Hocam,

3 yıldır yarı profesyonel ilgilendiğim yazılımı yaklaşık 1 sene önce bıraktım, tıp okuyorum şuanda. Maalesef yardımcı olamayacağım :(

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: Erhan Yaşar ***@***.***>
Gönderildi: Tuesday, February 6, 2024 12:08:25 PM
Kime: kaantoprakk/roulette-animation ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [kaantoprakk/roulette-animation] Needs comments about variables and figures involved in computations (Issue #1)


Kaan merhaba,

Burayı sana erişmek için kullanmak istedim. Yeniden yazmaya çalışırken hesaplamanın anlamlandıramadığım sabit değerleri mevcut. Misal assets/roulette.js: 126 ile belirttiğin 825 & 1125.

Github profilimdeki websitem üzerinden gerekirse telefonla arayarak ulaşabilirsen, bir projemde kullanmak üzere gerekirse ücreti karşılığında bilgi almak istiyorum mümkünse.

Sevgiler.

**Comment by erhanyasar** [comment]
Peki, çok teşekkür ederim <3.
